version: '3'
services:
  app:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: moi-coucou-app
    expose:
      - "80"
    networks:
      - caddy
      - default
    labels:
      caddy: coucou.zordak.fr
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
